### ISSUE TITLE
Undefined functions?

### ISSUE THREAD

**Issue by ryanpcmcquen** [mickael-kerjean/codemirror-orgmode#1]
Where are these defined?
```
org_cycle
org_shifttab
```

**Comment by ryanpcmcquen** [comment]
@mickael-kerjean, ping.

**Comment by mickael-kerjean** [comment]
[here](https://github.com/mickael-kerjean/filestash/blob/master/client/pages/viewerpage/editor/emacs-org.js#L1-L4) and [here](https://github.com/mickael-kerjean/filestash/blob/master/client/pages/viewerpage/editor/emacs-org.js#L20-L30)
